### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by jinzhongjia** [niuiic/format.nvim#2]
我看见你的仓库中有使用中文打字，我就直接用中文说明问题了

插件在格式化时都会创建一个tempfile进行格式化吗？
还是针对某些支持stdin的插件做了处理，可以从标准输入输出传递代码呢

**Comment by jinzhongjia** [comment]
有这个疑问的原因是，文件的io速度要慢很多，我认为如果能优先从stdin输入格式化，应当优先使用stdin

**Comment by niuiic** [comment]
都会创建临时文件

文件大小合理的情况下速度完全不是问题，至少人感觉不出区别，更何况是异步操作

为什么要创建文件也说明了，这个插件不仅仅是用来格式化的，有些命令没有文件无法运行，如果要区别对待的话既麻烦也容易出问题，另外这样做也有利于用户自定义工具
